version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/config/web/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
  php:
    build: ./docker/dockerfiles/php/
    volumes:
      - .:/app
      - ./docker/config/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - internal
      - database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
     - database
networks:
  internal:
    driver: bridge
  database:
    driver: bridge
