version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/config/web/site.conf:/etc/nginx/conf.d/site.conf
  php:
    image: php:7.1-fpm
    volumes:
      - .:/app
      - ./docker/config/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
